/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "login": [],
    "login.store": [],
    "logout": [],
    "password.request": [],
    "password.reset": [
        {
            "name": "token",
            "required": true
        }
    ],
    "password.email": [],
    "password.update": [],
    "register": [],
    "register.store": [],
    "verification.notice": [],
    "verification.verify": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "hash",
            "required": true
        }
    ],
    "verification.send": [],
    "password.confirm": [],
    "password.confirmation": [],
    "password.confirm.store": [],
    "home": [],
    "two-factor.email.challenge": [],
    "two-factor.email.verify": [],
    "two-factor.email.resend": [],
    "dashboard": [],
    "two-factor.method.set": [],
    "peminjaman.index": [],
    "peminjaman.poll": [],
    "peminjaman.store": [],
    "peminjaman.update": [
        {
            "name": "peminjaman",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.peminjaman.index": [],
    "admin.peminjaman.setujui": [
        {
            "name": "peminjaman",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.peminjaman.tolak": [
        {
            "name": "peminjaman",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.peminjaman.kembalikan": [
        {
            "name": "peminjaman",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.users.index": [],
    "admin.users.store": [],
    "admin.users.update": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.users.destroy": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.users.toggle-status": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.laporan.index": [],
    "profile.edit": [],
    "profile.update": [],
    "profile.destroy": [],
    "security.edit": [],
    "user-password.update": [],
    "appearance.edit": [],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ],
    "storage.local.upload": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
